const BOGOTA_COLLECTION_CENTER_CODE = 'CA001';
const MEDELLIN_COLLECTION_CENTER_CODE = 'CA004';
const CALI_COLLECTION_CENTER_CODE = 'CA006';
const BARRANQUILLA_COLLECTION_CENTER_CODE = 'CA002';
const DEFAULT_COLLECTION_CENTER_CODE = 'CA001';

const BOGOTA_CODE = '11001';
const SOACHA_CODE = '25754';
const MEDELLIN_CODE = '05001';
const ITAGUI_CODE = '05360';
const BELLO_CODE = '05088';
const SABANETA_CODE = '05631';
const LA_ESTRELLA_CODE = '05380';
const ENVIGADO_CODE = '05266';
const CALI_CODE = '76001';
const BARRANQUILLA_CODE = '08001';
const SOLEDAD_CODE = '08758';

const codesByCity: {[key: string]: string} = {
  [BOGOTA_CODE]: BOGOTA_COLLECTION_CENTER_CODE,
  [SOACHA_CODE]: BOGOTA_COLLECTION_CENTER_CODE,
  [MEDELLIN_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [ITAGUI_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [BELLO_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [ENVIGADO_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [LA_ESTRELLA_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [SABANETA_CODE]: MEDELLIN_COLLECTION_CENTER_CODE,
  [CALI_CODE]: CALI_COLLECTION_CENTER_CODE,
  [BARRANQUILLA_CODE]: BARRANQUILLA_COLLECTION_CENTER_CODE,
  [SOLEDAD_CODE]: BARRANQUILLA_COLLECTION_CENTER_CODE,
};

export const getCollectionCenterCodeByCity = (
  cityCode: string | undefined,
): string => {
  return codesByCity?.[cityCode ?? ''] ?? DEFAULT_COLLECTION_CENTER_CODE;
};
