import { MCCCategories, StoreTypes } from "~/legacy/src/commons/enums/enums";

const storeTypesByMCCSubcategory: Record<number, number> = {
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_CATERING]:
    StoreTypes.RESTAURANTE_BAR_O_COMIDA_RAPIDA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_ABARROTES_MERCADO]:
    StoreTypes.SUPERMERCADO_O_TIENDA_DE_CONVENIENCIA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_BAR_CLUB_DISCOTECA]: StoreTypes.LICORERIA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_RESTAURANTE]:
    StoreTypes.RESTAURANTE_BAR_O_COMIDA_RAPIDA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_COMIDA_RAPIDA]:
    StoreTypes.RESTAURANTE_BAR_O_COMIDA_RAPIDA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_CAFE]:
    StoreTypes.RESTAURANTE_BAR_O_COMIDA_RAPIDA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_CIGARRERIA]: StoreTypes.TIENDA_DE_BARRIO,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_REPOSTERIA_PANADERIA]:
    StoreTypes.MINIMERCADO_1_CAJA_REGISTRADORA,
  [MCCCategories.ALIMENTOS_Y_BEBIDAS_LICORES]: StoreTypes.LICORERIA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_SPA]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_SUPLEMENTOS]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_DISTRIBUIDORA]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_SALON_DE_BELLEZA]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_ESTILISTA_INDEPENDIENTE]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_MASAJISTA_INDEPENDIENTE]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_CENTRO_DE_TATUAJES]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.BELLEZA_Y_CUIDADO_PERSONAL_OTRO]: StoreTypes.OTROS,
  [MCCCategories.COMERCIO_DETALLISTA_EQUIPOS_MEDICOS]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_ELEMENTOS_DEL_HOGAR]:
    StoreTypes.ARTICULOS_PARA_EL_HOGAR,
  [MCCCategories.COMERCIO_DETALLISTA_JUGUETERIA_PIÑATERIA]:
    StoreTypes.VENTA_DE_JUGUETES_O_LIBROS,
  [MCCCategories.COMERCIO_DETALLISTA_FARMACIA]: StoreTypes.FARMACIA_Y_DROGUERIA,
  [MCCCategories.COMERCIO_DETALLISTA_JOYERIA]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_FLORISTERIA]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_INSUMOS]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_AUTO_PARTES]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.COMERCIO_DETALLISTA_ARTESANIAS]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_MUEBLES_DECORACION]:
    StoreTypes.ARTICULOS_PARA_EL_HOGAR,
  [MCCCategories.COMERCIO_DETALLISTA_TECNOLOGIA]:
    StoreTypes.ELECTRONICA_E_INFORMATICA,
  [MCCCategories.COMERCIO_DETALLISTA_REVENDEDOR]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.COMERCIO_DETALLISTA_ROPA_ACCESORIOS]:
    StoreTypes.ROPA_ZAPATOS_Y_ACCESORIOS,
  [MCCCategories.COMERCIO_DETALLISTA_OTRO]: StoreTypes.OTROS,
  [MCCCategories.COMERCIO_DETALLISTA_MATERIALES_DE_CONSTRUCCION]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_MAQUINARIA]:
    StoreTypes.INDUSTRIA_O_MANUFACTURA,
  [MCCCategories.COMERCIO_DETALLISTA_PERFUMERIA]:
    StoreTypes.ARTICULOS_DE_BELLEZA,
  [MCCCategories.COMERCIO_DETALLISTA_MASCOTAS]:
    StoreTypes.TIENDA_DE_MASCOTAS_O_VETERINARIA,
  [MCCCategories.COMERCIO_DETALLISTA_LIBROS_PAPELERIA]:
    StoreTypes.VENTA_DE_JUGUETES_O_LIBROS,
  [MCCCategories.COMERCIO_DETALLISTA_ELEMENTOS_DE_SEGURIDAD]: StoreTypes.OTROS,
  [MCCCategories.COMERCIO_DETALLISTA_TIENDA_DE_DEPORTES]:
    StoreTypes.ROPA_ZAPATOS_Y_ACCESORIOS,
  [MCCCategories.COMERCIO_DETALLISTA_VENTA_DE_VEHICULOS_USADOS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.COMERCIO_DETALLISTA_VENTA_DE_VEHICULOS_NUEVOS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.COMERCIO_DETALLISTA_VENTA_POR_CATALOGO]:
    StoreTypes.VENTA_POR_CATALOGO,
  [MCCCategories.COMERCIO_DETALLISTA_VENTA_DE_BICICLETAS_Y_ACCESORIOS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.COMERCIO_DETALLISTA_TIENDA_NATURISTA]:
    StoreTypes.TIENDA_NATURISTA,
  [MCCCategories.EDUCACION_SERVICIOS_DE_NIÑERA]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.EDUCACION_OTRO]: StoreTypes.OTROS,
  [MCCCategories.EDUCACION_TALLERES_CURSOS_CAPACITACIONES]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.EDUCACION_JARDIN_INFANTIL]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.EDUCACION_COLEGIOS]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.EDUCACION_TUTOR_PROFESOR]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.REPARACION_Y_LIMPIEZA_LAVANDERIA]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.REPARACION_Y_LIMPIEZA_LIMPIEZA_DEL_HOGAR]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.REPARACION_Y_LIMPIEZA_REPARACIONES_LOCATIVAS]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.REPARACION_Y_LIMPIEZA_OTRO]: StoreTypes.OTROS,
  [MCCCategories.REPARACION_Y_LIMPIEZA_MODA_ZAPATERIA]:
    StoreTypes.ROPA_ZAPATOS_Y_ACCESORIOS,
  [MCCCategories.REPARACION_Y_LIMPIEZA_AUTOMOTRIZ_Y_AUTOPARTES]:
    StoreTypes.TALLER_AUTOMOTRIZ,
  [MCCCategories.SERVICIOS_OTRO]: StoreTypes.OTROS,
  [MCCCategories.SERVICIOS_OPTICAS]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_SEGUROS]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_DISEÑO_FOTOGRAFIA]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_MEDICINA_ODONTOLOGIA]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_MENSAJERIA]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_LOGISTICA]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.SERVICIOS_TERAPIAS]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_TECNOLOGIA_Y_SOFTWARE]:
    StoreTypes.ELECTRONICA_E_INFORMATICA,
  [MCCCategories.SERVICIOS_VETERINARIA]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_CARPINTERIA]: StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_ARQUITECTURA_E_INGENIERIA]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_CONTABILIDAD_ASESORIAS]:
    StoreTypes.SERVICIOS_PROFESIONALES,
  [MCCCategories.SERVICIOS_AUTOLAVADO]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_MUDANZA]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_MOTOTAXI]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_TAXI]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_OTRO]: StoreTypes.OTROS,
  [MCCCategories.TRANSPORTE_BUS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_ALQUILER_DE_VEHICULOS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_DOMICILIOS]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TRANSPORTE_SERVICIO_ESPECIAL]:
    StoreTypes.SERVICIOS_DE_TRANSPORTE_Y_LOGISTICA,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_AGENCIA_DE_VIAJES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_CENTROS_CULTURALES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_CENTRO_DE_RECREACION_Y_DEPORTE]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_MOTELES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_ENTRETENIMIENTO]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_HOTELES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_ENTRENADOR_PERSONAL]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_TOURS]: StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_EVENTOS_FESTIVALES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_HOSTALES]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_PAQUETES_TURISTICOS]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_TURISMO]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_HOSPEDAJE]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_GIMNASIO]:
    StoreTypes.HOTELES_Y_TURISMO,
  [MCCCategories.TURISMO_Y_ENTRETENIMIENTO_VIDEOJUEGOS]:
    StoreTypes.VENTA_DE_JUGUETES_O_LIBROS,
};

const mccSubcategoriesByStoreType = (
  Object.entries(storeTypesByMCCSubcategory) as number[][]
).reduce<Record<number, number[]>>(
  (acc: Record<number, number[]>, item: number[]): Record<number, number[]> => {
    if (acc?.[item[0]]) {
      acc[item[0]] = [...acc[item[0]], item[1]];
    } else {
      acc[item[0]] = [item[1]];
    }
    return acc;
  },
  {} as Record<number, number[]>
);

export const getStoreTypeByMCCSubcategoryId = (subcategoryId: number): number =>
  storeTypesByMCCSubcategory?.[subcategoryId] ?? StoreTypes.OTROS;

export const getMCCSubcategoryByStoreTypeId = (
  storeTypeId: number
): number[] | undefined => {
  return mccSubcategoriesByStoreType?.[storeTypeId];
};
