export const NoCommissionCities: {name: string; stateCode: string}[] = [
  {name: 'Caldas', stateCode: '017'},
  {name: 'Caquetá', stateCode: '018'},
  {name: 'Cauca', stateCode: '019'},
  {name: 'Chocó', stateCode: '027'},
  {name: 'Huila', stateCode: '041'},
  {name: 'La Guajira', stateCode: '044'},
  {name: 'Meta', stateCode: '050'},
  {name: 'Risaralda', stateCode: '066'},
  {name: 'Arauca', stateCode: '081'},
  {name: 'Casanare', stateCode: '085'},
  {name: 'Putumayo', stateCode: '086'},
  {
    name: 'Archipiélago de San Andrés, Providencia y Santa Ca',
    stateCode: '088',
  },
  {name: 'Amazonas', stateCode: '091'},
  {name: 'Guainía', stateCode: '094'},
  {name: 'Guaviare', stateCode: '095'},
  {name: 'Vaupés', stateCode: '097'},
  {name: 'Vichada', stateCode: '099'},
];
